config/routes.rb
Rails.application.routes.draw do
  get 'search', to: "search#search"
  # get 'relationships/create'
  # get 'relationships/destroy'
  # get 'comments/create'
  # get 'comments/destroy'
  root to: 'users#home'
  # deviseのコントローラーをカスタマイズしたのでroutesを編集しないと反映されない
  devise_for :users, :controllers => {
    :registrations => 'users/registrations',
    :sessions => 'users/sessions'
  }

  resources :users do
    resource :relationships, only: [:create, :destroy]
    get :follows, on: :member
    get :followers, on: :member
  end

  resources :books do
    resource :favorites, only: [:create, :destroy]
    resource :comments, only: [:create, :destroy]
  end
  resources :home
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  validates :name, presence: true, length: { minimum: 2, maximum: 20 }
  validates :introduction, length: { maximum: 50 }
  attachment :profile_image

  has_many :books, dependent: :destroy

  has_many :favorites
  has_many :favorite_books, through: :favorites, source: :book

  has_many :comments
  has_many :comment_books, through: :comments, source: :book

  has_many :active_relationships, class_name: 'Relationship', foreign_key: :following_id
  has_many :followings, through: :active_relationships, source: :follower

  has_many :passive_relationships, class_name: 'Relationship', foreign_key: :follower_id
  has_many :followers, through: :passive_relationships, source: :following

  def followed_by?(user)
    passive_relationships.find_by(following_id: user.id).present?
  end

  def self.search(search, select_type)
    case select_type
    when '1' # 完全一致
      User.where(['name LIKE ?', "#{search}"])
    when '2' # 前方一致
      User.where(['name LIKE ?', "#{search}%"])
    when '3' # 後方一致
      User.where(['name LIKE ?', "%#{search}"])
    else # 部分一致
      User.where(['name LIKE ?', "%#{search}%"])
    end
  end

  include JpPrefecture
  jp_prefecture :prefecture_code

  def prefecture_name
    JpPrefecture::Prefecture.find(code: prefecture_code).try(:name)
  end

  def prefecture_name=(prefecture_name)
    self.prefecture_code = JpPrefecture::Prefecture.find(name: prefecture_name).code
  end
end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/plataformatec/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  def create
    super
    # resourceにsign_upしたユーザーの情報が入っている
    SignupMailer.creation_email(resource).deliver_now

  end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!, only: [:show, :index, :edit, :update, :user_params]
  before_action :ensure_correct_user,only: [:edit]

  def home
    render :home
  end

  def show
    @user = User.find(params[:id])
    @book = Book.new
    @books = @user.books.all
    @favorite_books = @user.favorite_books
    @comments = @user.comments
  end

  def index
    @user = current_user
    @book = Book.new
    @users = User.all

  end

  def ensure_correct_user
    @user = User.find(params[:id])
    if @user != current_user
      redirect_to user_path(current_user)
    else
      render :edit
    end
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      redirect_to user_path(@user.id), notice:'You have updated user successfully.'
    else
      render :edit
    end
  end

  def follows
    user = User.find(params[:id])
    @users = user.followings
  end

  def followers
    user = User.find(params[:id])
    @users = user.followers
  end

  private
  def user_params
    params.require(:user).permit(:name, :email, :profile_image, :introduction, :postcode, :prefecture_name, :address_city, :address_street, :address_building)
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/edit.html.erb
<div class="container">
  <h1>User info</h1>



  <% if @user.errors.any? %>
      <h3>入力した内容にerrorが<%= @user.errors.count %>件あります</h3>
      <ul>
        <% @user.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
  <% end %>

  <%= form_for(@user) do |f| %>
    <div class="field">
        <label>Name</label>
            <%= f.text_field :name, autofocus: true, id:"inputEmail", placeholder:"名前"%>
        <span class="fa fa-user form-control-icon" aria-hidden="true"></span>
    </div>

    <div class="field">
        <label>Image</label>
        <%= attachment_image_tag @user, :profile_image,　format: 'jpeg', size: "100x100" %>
        <%= f.attachment_field :profile_image, placeholder: "プロフィール画像", class: "user-edit-form" %>
    </div>

    <div class="field">
        <label>Introduction</label>
        <%= f.text_area :introduction, class: "user-edit-form" %>
    </div>

    <div class="field">
      <%= f.submit "Update User", class:"" %>
    </div>

  <% end %>

</div>

app/views/users/followers.html.erb
<h1>Follower Users</h1>

    <div class="main col-lg-9">
        <h1>Users</h1>
        <table class="table">
            <thead>
                <tr>
                    <th>image</th>
                    <th>name</th>
                    <th>フォロー数</th>
                    <th>フォロワー数</th>
                    <th></th>
                    <th></th>
                </tr>
            </thead>

            <% @users.each do |user| %>
                <tr>
                    <td>
                        <%= attachment_image_tag user, :profile_image, :fill, 50, 50, format: 'jpeg', class: "img-thumnail pull-left profile-img", fallback: "no_image.jpg", size:'40x40' %>
                    </td>

                    <td>
                        <p><%= user.name %></p>
                    </td>

                    <td>
                        <p>フォロー数: <%= user.active_relationships.where(following_id: user.id).count %></p>
                    </td>

                    <td>
                        <p>フォロワー数: <%= user.passive_relationships.all.count %></p>
                    </td>

                    <td>
                        <% if user != current_user %>
                            <% if user.followed_by?(current_user) %>
                                <%= link_to "フォローを外す", user_relationships_path(user.id), method: :delete %>
                            <% else %>
                                <%= link_to "フォローする", user_relationships_path(user.id), method: :post %>
                            <% end %>
                        <% end %>
                    </td>
                    <td></td>

                    <td>
                        <%= link_to user_path(user) do %>
                            <p>Show</p>
                        <% end %>
                    </td>
                </tr>
            <% end %>
        </table>
    </div>

app/views/users/follows.html.erb
<h1>Following Users</h1>

    <div class="main col-lg-9">
        <h1>Users</h1>
        <table class="table">
            <thead>
                <tr>
                    <th>image</th>
                    <th>name</th>
                    <th>フォロー数</th>
                    <th>フォロワー数</th>
                    <th></th>
                    <th></th>
                </tr>
            </thead>

            <% @users.each do |user| %>
                <tr>
                    <td>
                        <%= attachment_image_tag user, :profile_image, :fill, 50, 50, format: 'jpeg', class: "img-thumnail pull-left profile-img", fallback: "no_image.jpg", size:'40x40' %>
                    </td>

                    <td>
                        <p><%= user.name %></p>
                    </td>

                    <td>
                        <p>フォロー数: <%= user.active_relationships.where(following_id: user.id).count %></p>
                    </td>

                    <td>
                        <p>フォロワー数: <%= user.passive_relationships.all.count %></p>
                    </td>

                    <td>
                        <% if user != current_user %>
                            <% if user.followed_by?(current_user) %>
                                <%= link_to "フォローを外す", user_relationships_path(user.id), method: :delete %>
                            <% else %>
                                <%= link_to "フォローする", user_relationships_path(user.id), method: :post %>
                            <% end %>
                        <% end %>
                    </td>
                    <td></td>

                    <td>
                        <%= link_to user_path(user) do %>
                            <p>Show</p>
                        <% end %>
                    </td>
                </tr>
            <% end %>
        </table>
    </div>

app/views/users/home.html.erb
<p class="col-md-offset-1"><%= notice %></p>
<div class="container col-md-7 col-md-offset-3">
  <div class="row">
  <h1>welcome to <span class="glyphicon glyphicon-book" aria-hidden="true"></span>Bookers !!
</h1>
</div>

  <div class="row home-text">
<p  style="line-height: 30px;">In<span class="glyphicon glyphicon-book" aria-hidden="true"></span><strong> Bookers,</strong><br>
you can share and exchange your opinions , inpressions , and emotions<br>
about various books!<br>
</p>
  </div>



  <div class="row">
    <div><%= link_to "Log in", new_user_session_path, class: "btn btn-info col-lg-8" %></div>
  </div>


  <div class="row">
    <div><%= link_to "Sign up", new_user_registration_path, class: "btn btn-success col-lg-8" %></div>
  </div>

</div>

app/views/users/index.html.erb
<div class="container">
    <%# そもそもログインしてなきゃいろんな画面に入れないから不要 %>
    <% if user_signed_in? %>
        <%= render "/search_box" %>
    <% end %>

    <div class="sidebar col-lg-3">

        <div class="row">
            <h1 class="row">User info</h1>

            <div class="profile-container row">
                <%= attachment_image_tag @user, :profile_image, :fill, 100, 100, class: "img-thumnail pull-left profile-thumb", fallback: "no_image.jpg"%>
            </div>

            <table class="table">
                <tr>
                    <th>name</th>
                    <th class="profile-name"><%= @user.name %></th>
                </tr>

                <tr>
                    <th>introduction</th>
                    <th class="profile-introduction"><%= @user.introduction %></th>
                </tr>
                <tr>
                    <th>フォロー数</th>
                    <th><%= link_to @user.active_relationships.all.count, follows_user_path(@user) %></th>
                </tr>
                <tr>
                    <th>フォロワー数</th>
                    <th><%= link_to @user.passive_relationships.all.count, followers_user_path(@user) %></th>
                </tr>
            </table>

            <div>
            <%= link_to "", edit_user_path(@user), class: "glyphicon glyphicon-wrench btn btn-default col-lg-12", style:"color: black" %>
            </div>

        </div>


        <div class="row">
            <%= form_for(@book, url: books_path) do |f| %>
                <div>
                    <% if @book.errors.any? %>
                      <div id="error_explanation">
                        <h2><%= @book.errors.count %>件のエラーが発生しました。</h2>
                        <ul>
                            <% @book.errors.full_messages.each do |message| %>
                              <li><%= message %></li>
                            <% end %>
                        </ul>
                      </div>
                    <% end %>
                </div>

                <h1 class="">New book</h1>

                <div class="row">
                    <h5>Title</h5>
                    <div><%= f.text_field :title, class: "col-lg-12"  %></div>
                </div>

                <div class="row">
                    <h5>Opinion</h5>
                     <div><%= f.text_area :body, class: "col-lg-12"  %></div>
                </div>

                <div class="row">
                    <div style="margin-top: 10px;"><%= f.submit "Create Book", class: "btn btn-primary col-lg-12" %></div>
                </div>
            <% end %>

        </div>
    </div>


    <div class="main col-lg-9">
        <h1>Users</h1>
        <table class="table">
            <thead>
                <tr>
                    <th>image</th>
                    <th>name</th>
                    <th>フォロー数</th>
                    <th>フォロワー数</th>
                    <th></th>
                    <th></th>
                </tr>
            </thead>

            <% @users.each do |user| %>
                <tr>
                    <td>
                        <%= attachment_image_tag user, :profile_image, :fill, 50, 50, format: 'jpeg', class: "img-thumnail pull-left profile-img", fallback: "no_image.jpg", size:'40x40' %>
                    </td>

                    <td>
                        <p><%= user.name %></p>
                    </td>

                    <td>
                        <p>フォロー数: <%= user.active_relationships.all.count %></p>
                    </td>

                    <td>
                        <p>フォロワー数: <%= user.passive_relationships.all.count %></p>
                    </td>

                    <td>
                        <% if user != current_user %>
                            <% if user.followed_by?(current_user) %>
                                <%= link_to "フォローを外す", user_relationships_path(user.id), method: :delete %>
                            <% else %>
                                <%= link_to "フォローする", user_relationships_path(user.id), method: :post %>
                            <% end %>
                        <% end %>
                    </td>
                    <td></td>

                    <td>
                        <%= link_to user_path(user) do %>
                            <p>Show</p>
                        <% end %>
                    </td>
                </tr>
            <% end %>
        </table>
    </div>
</div>

app/views/users/show.html.erb
<div class="container">
    <%# そもそもログインしてなきゃいろんな画面に入れないから不要 %>
    <% if user_signed_in? %>
        <%= render "/search_box" %>
    <% end %>

<p><%= notice %></p>
    <div class="sidebar col-lg-3">

        <div class="row">
            <h1 class="row">User info</h1>

            <div class="profile-container row">
                <%= attachment_image_tag @user, :profile_image, :fill, 100, 100, class: "img-thumnail pull-left profile-thumb", fallback: "no_image.jpg"%>
            </div>

            <table class="table">
                <tr>
                    <th>name</th>
                    <th class="profile-name"><%= @user.name %></th>
                </tr>

                <tr>
                    <th>introduction</th>
                    <th class="profile-introduction"><%= @user.introduction %></th>
                </tr>
                <tr>
                    <th>フォロー数</th>
                    <th><%= link_to @user.active_relationships.all.count, follows_user_path(@user) %></th>
                </tr>
                <tr>
                    <th>フォロワー数</th>
                    <th><%= link_to @user.passive_relationships.all.count, followers_user_path(@user) %></th>
                </tr>


            </table>
            <div>
                <% if @user != current_user %>
                    <% if @user.followed_by?(current_user) %>
                        <%= link_to "フォローを外す", user_relationships_path(@user.id), class: "btn btn-default col-lg-12", method: :delete %>
                    <% else %>
                        <%= link_to "フォローする", user_relationships_path(@user.id), class: "btn btn-default col-lg-12", method: :post %>
                    <% end %>
                <% end %>
            </div>
            <div>
            <%= link_to "", edit_user_path(@user), class: "glyphicon glyphicon-wrench btn btn-default col-lg-12", style:"color: black" %>
            </div>

        </div>


        <div class="row">
            <%= form_for(@book, url: books_path) do |f| %>
                <div>
                    <% if @book.errors.any? %>
                      <div id="error_explanation">
                        <h2><%= @book.errors.count %>件のエラーが発生しました。</h2>
                        <ul>
                            <% @book.errors.full_messages.each do |message| %>
                              <li><%= message %></li>
                            <% end %>
                        </ul>
                      </div>
                    <% end %>
                </div>

                <h1 class="">New book</h1>

                <div class="row">
                    <h5>Title</h5>
                    <div><%= f.text_field :title, class: "col-lg-12"  %></div>
                </div>

                <div class="row">
                    <h5>Opinion</h5>
                     <div><%= f.text_area :body, class: "col-lg-12"  %></div>
                </div>

                <div class="row">
                    <div style="margin-top: 10px;"><%= f.submit "Create Book", class: "btn btn-primary col-lg-12" %></div>
                </div>
            <% end %>

        </div>
    </div>

    <div class="main col-lg-9">
        <h1>Books</h1>
        <table class="table">

                <thead>
                    <tr>
                        <th></th>
                        <th>Title</th>
                        <th>Opinion</th>
                    </tr>
                </thead>

            <% @books.each do |book| %>
                <tr>
                    <td>
                    <%= link_to user_path(book.user_id) do %>
                        <%= attachment_image_tag book.user, :profile_image, :fill, 50, 50, class: "img-thumnail pull-left profile-thumb", fallback: "no_image.jpg",size: '50x50' %>
                    <% end %>
                    </td>

                    <td>
                        <%= link_to book_path(book) do %>
                            <div><%= book.title %></div>
                        <% end %>
                    </td>

                    <td>
                        <div><%= book.body %></div>
                    </td>
                </tr>
            <% end %>
        </table>
        <h1>Favorites</h1>
        <table class="table">
            <thead>
                <tr>
                    <th>Title</th>
                    <th>Opinion</th>
                </tr>
            </thead>
            <tbody>
                <% @favorite_books.each do |book| %>
                    <tr>
                        <td><%= link_to "#{book.title}", book_path(book) %></td>
                        <td><%= link_to "#{book.body}", book_path(book) %></td>
                    </tr>
                <% end %>
            </tbody>
        </table>

        </table>
        <h1>Comments</h1>
        <h3><%= "全#{@user.comments.count}件" %></h3>
        <table class="table">
            <thead>
            </thead>
            <tbody>
                <% @comments.each do |c| %>
                    <tr>
                        <td><%= c.body %></td>
                        <% if c.user == current_user %>
                            <td>
                                <%= link_to "Delete", book_comments_path(c.book_id, comment_id: c.id, user_id:params[:id],  page: "show"), class: "btn-sm btn-success", method: :delete %>
                            </td>
                        <% end %>
                    </tr>
                <% end %>
            </tbody>
        </table>
    </div>
</div>

<% if @user == current_user %>
    <div class="container">
        <div id="map"></div>
        <div id="address" style="display: none;"><%= @user.prefecture_name + @user.address_city + @user.address_street + @user.address_building %></div>
    </div>
    <script src=<%= "https://maps.googleapis.com/maps/api/js?key=#{ENV['KEY']}&callback=initMap" %> async defer></script>
<% end %>