config/routes.rb
Rails.application.routes.draw do
  get 'search', to: "search#search"
  # get 'relationships/create'
  # get 'relationships/destroy'
  # get 'comments/create'
  # get 'comments/destroy'
  root to: 'users#home'
  # deviseのコントローラーをカスタマイズしたのでroutesを編集しないと反映されない
  devise_for :users, :controllers => {
    :registrations => 'users/registrations',
    :sessions => 'users/sessions'
  }

  resources :users do
    resource :relationships, only: [:create, :destroy]
    get :follows, on: :member
    get :followers, on: :member
  end

  resources :books do
    resource :favorites, only: [:create, :destroy]
    resource :comments, only: [:create, :destroy]
  end
  resources :home
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/book.rb
class Book < ApplicationRecord
  belongs_to :user
  validates :title, presence: true
  validates :body, presence: true, length: { maximum: 200 }

  has_many :favorites
  has_many :comments

  def favorited_by?(user)
    favorites.where(user_id: user.id).exists?
  end

  def commented_by?(user)
    comments.where(user_id: user.id).exists?
  end

  def comment_user(book)
    @comment_user = User.where(book.comments.user_id).name
  end

  def self.search(search, select_type)
    case select_type
    when '1' # 完全一致
      Book.where(['title LIKE ?', "#{search}"])
    when '2' # 前方一致
      Book.where(['title LIKE ?', "#{search}%"])
    when '3' # 後方一致
      Book.where(['title LIKE ?', "%#{search}"])
    else # 部分一致
      Book.where(['title LIKE ?', "%#{search}%"])
    end
  end

end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :authenticate_user!
  before_action :ensure_correct_user,only: [:edit]

  def create
    @book = Book.new(book_params)

    @book.user_id = current_user.id
    if @book.save
      redirect_to @book, notice: 'You have creatad book successfully.'
    else
      @books = Book.all
      render :index
    end
  end

  def index
    @books = Book.all
    @user_id = current_user.id

    @book = Book.new

  end

  def show
    @book = Book.find(params[:id])
    @books = Book.all
    @book_new = Book.new
    # @comment = current_user.comments.build(book_id: params[:book_id])
    @comment = Comment.new
  end

  def ensure_correct_user
    @book = Book.find(params[:id])
    if @book.user_id != current_user.id
      redirect_to books_path
    end

  end

  def edit
    @book = Book.find(params[:id])
  end

  def update
    @book = Book.find(params[:id])
    if @book.update(book_params)
    redirect_to book_path(@book.id), notice: "You have updated book successfully."
    else
    render :edit
    end
  end

  def destroy
    @book = Book.find(params[:id])
    if @book.destroy
    redirect_to books_path
    else
      render :edit
    end
  end

  private
  def book_params
    params.require(:book).permit(:title, :body)
  end
end

app/helpers/books_helper.rb
module BooksHelper
end

app/views/books/_book.html.erb
                <tr>
                    <td>
                    <%= link_to user_path(book.user_id) do %>
                        <%= attachment_image_tag book.user, :profile_image, :fill, 50, 50, class: "img-thumnail pull-left profile-thumb", fallback: "no_image.jpg",size: '40x40' %>
                    <% end %>
                    </td>

                    <td>
                        <%= link_to book_path(book) do %>
                            <div><%= book.title %></div>
                        <% end %>
                    </td>

                    <td>
                        <div><%= book.body %></div>
                    </td>

                    <td>
                        <div id=<%= "book-#{book.id}" %>>
                            <%= render "favorite", book: book %> <!-- render先の_favoriteで使うbookにbookを渡す -->
                        </div>
                    </td>

                    <td>
                        <div>
                            <p><%= "コメント数: #{book.comments.count}" %></p>
                        </div>
                    </td>

                </tr>

app/views/books/_book_detail.html.erb
    <h1>Book detail</h1>
        <table class="table">
            <tr>
                <td>
                    <%= link_to user_path(book.user) do %>
                        <%= attachment_image_tag book.user, :profile_image, :fill, 40, 40, format: 'jpeg', class: "img-thumnail", fallback: "no_image.jpg", size:"40x40" %><br>
                        <%= book.user.name %>
                    <% end %>
                </td>
                <td>
                    <%= link_to book_path(book.id) do %>
                    <%= book.title %>
                    <% end %>
                </td>
                <td>
                    <%= book.body %>
                </td>

                    <td>
                        <div id=<%= "book-#{book.id}" %>>
                            <%= render "books/favorite", book: book %> <!-- render先の_favoriteで使うbookにbookを渡す -->
                        </div>
                    </td>

                    <td>
                        <div>
                            <p><%= "コメント数: #{book.comments.count}" %></p>
                        </div>
                    </td>

                <% if book.user == current_user %>
                <td>
                     <%= link_to "Edit", edit_book_path, class: "btn-sm btn-success" %>
                </td>
                <td>
                    <%= link_to "Destroy", book_path(book), class: "btn-sm btn-danger", method: :delete, data: {confirm: '本当に消しますか？'} %>
                </td>
            <% end %>
            </tr>
        </table>

        <div>
            <%# urlを書かなくても自動予測してくれるはずだが、なぜかbook_comment_pathを参照していたので明記した %>
            <%= form_with(model:[book, comment],url: book_comments_path(book,comment)) do |f| %>
                <%= f.text_area :body, placeholder: 'コメントを入力', class: "form", size: "90x5" %>
                <%= f.submit %>
            <% end %>
        </div>

        <table class="table">
            <h1>Comments</h1>
            <thead>
                <tr>
                    <th>名前</th>
                    <th>コメント</th>
                    <th></th>
                </tr>
            </thead>
            <% book.comments.each do |c| %>
                <tr>
                    <td>
                        <%= c.user.name %>
                    </td>
                    <td>
                        <%= c.body %>
                    </td>
                    <% if c.user == current_user %>
                        <td>
                            <%= link_to "Delete", book_comments_path(c.book_id, comment_id: c), class: "btn-sm btn-success", method: :delete, remote: :true %>
                        </td>
                    <% end %>
                </tr>
            <% end %>
        </table>

app/views/books/_favorite.html.erb
<% if book.favorited_by?(current_user) %>
    <%= link_to book_favorites_path(book.id), method: :delete, remote: :true do %> <!-- remote: :trueでAjaxリクエストを飛ばす -->
        <i class="fas fa-heart"></i>
        <%= book.favorites.count %>
    <% end %>
<% else %>
    <%= link_to book_favorites_path(book.id), method: :post, remote: :true do %> <!-- remote: :trueでAjaxリクエストを飛ばす -->
        <i class="far fa-heart"></i>
        <%= book.favorites.count %>
    <% end %>
<% end %>

app/views/books/edit.html.erb
<div class="container">
    <div class="col-md-6 col-md-offset-3" >
      <h1>Editing Book</h1>

      <%= form_for(@book) do |f| %>
          <div>
              <% if @book.errors.any? %>
                <div id="error_explanation">
                  <h2><%= @book.errors.count %>件のerrorが発生しました。</h2>
                  <ul>
                      <% @book.errors.full_messages.each do |message| %>
                        <li><%= message %></li>
                      <% end %>
                  </ul>
                </div>
              <% end %>
          </div>

          <div class="row">
              <h5>Title</h5>
              <div><%= f.text_field :title, class: "col-lg-12"  %></div>
          </div>

          <div class="row">
              <h5>Opinion</h5>
               <div><%= f.text_area :body, class: "col-lg-12"  %></div>
          </div>

          <div class="row">
              <div style="margin-top: 10px; margin-bottom: 55px;"><%= f.submit "Update Book", class: "btn btn-primary col-lg-12" %></div>
          </div>
      <% end %>

      <%= link_to "Show", book_path(@book), class: ""  %>
      <span>|</span>
      <%= link_to "Back", books_path %>

    </div>

</div>

app/views/books/index.html.erb
<div class="container">
    <%# そもそもログインしてなきゃいろんな画面に入れないから不要 %>
    <% if user_signed_in? %>
        <%= render "/search_box" %>
    <% end %>

    <p><%= notice %></p>
    <div>
        <% if @book.errors.any? %>
            <div id="error_explanation">
                <h2><%= @book.errors.count %>件のerrorが発生しました。</h2>
                <ul>
                    <% @book.errors.full_messages.each do |message| %>
                    <li><%= message %></li>
                    <% end %>
                </ul>
            </div>
        <% end %>
    </div>

    <div class="sidebar col-lg-3">
        <div class="row">
            <h1 class="row">User info</h1>
            <div class="profile-container row">
                <%= attachment_image_tag current_user, :profile_image, :fill, 100, 100, class: "img-thumnail pull-left profile-thumb", fallback: "no_image.jpg"%>
            </div>
            <table class="table">
                <tr>
                    <th>name</th>
                    <th class="profile-name"><%= current_user.name %></th>
                </tr>
                <tr>
                    <th>introduction</th>
                    <th class="profile-introduction"><%= current_user.introduction %></th>
                </tr>
                <tr>
                    <th>フォロー数</th>
                    <th><%= link_to current_user.active_relationships.all.count, follows_user_path(current_user) %></th>
                </tr>
                <tr>
                    <th>フォロワー数</th>
                    <th><%= link_to current_user.passive_relationships.all.count, followers_user_path(current_user) %></th>
                </tr>
            </table>
            <div>
                <%= link_to "", edit_user_path(current_user), class: "glyphicon glyphicon-wrench btn btn-default col-lg-12", style:"color: black" %>
            </div>
        </div>


        <div class="row">
            <%= form_for(@book, url: books_path) do |f| %>


                <h1 class="">New book</h1>

                <div class="row">
                    <h5>Title</h5>
                    <div><%= f.text_field :title, class: "col-lg-12"  %></div>
                </div>

                <div class="row">
                    <h5>Opinion</h5>
                     <div><%= f.text_area :body, class: "col-lg-12"  %></div>
                </div>

                <div class="row">
                    <div style="margin-top: 10px;"><%= f.submit "Create Book", class: "btn btn-primary col-lg-12" %></div>
                </div>
            <% end %>

        </div>
    </div>

    <div class="main col-lg-9">
        <h1>Books</h1>
        <table class="table table-hover table-inverse">
            <thead>
                <tr>
                    <th></th>
                    <th>Title</th>
                    <th>Opinion</th>
                    <th></th>
                    <th></th>
                </tr>
            </thead>
                <% @books.each do |book| %>
                    <%= render 'book', book: book %> <!--render先の_book.html.erbで使うbookにeachで回すbookを渡す-->
                <% end %>
        </table>
    </div>
</div>

app/views/books/show.html.erb
<div class="container">
    <%# そもそもログインしてなきゃいろんな画面に入れないから不要 %>
    <% if user_signed_in? %>
        <%= render "/search_box" %>
    <% end %>

<p><%= notice %></p>
    <div class="sidebar col-lg-3">

        <div class="row">
            <h1 class="row">User info</h1>

            <div class="profile-container row">
                <%= attachment_image_tag @book.user, :profile_image, :fill, 100, 100, class: "img-thumnail pull-left profile-thumb", fallback: "no_image.jpg"%>
            </div>

            <table class="table">
                <tr>
                    <th>name</th>
                    <th class="profile-name"><%= @book.user.name %></th>
                </tr>

                <tr>
                    <th>introduction</th>
                    <th class="profile-introduction"><%= @book.user.introduction %></th>
                </tr>
                <tr>
                    <th>フォロー数</th>
                    <th><%= link_to @book.user.active_relationships.all.count, follows_user_path(@book.user) %></th>
                </tr>
                <tr>
                    <th>フォロワー数</th>
                    <th><%= link_to @book.user.passive_relationships.all.count, followers_user_path(@book.user) %></th>
                </tr>

            </table>

            <div>
                <% if @book.user != current_user %>
                    <% if @book.user.followed_by?(current_user) %>
                        <%= link_to "フォローを外す", user_relationships_path(@book.user.id), class: "btn btn-default col-lg-12", method: :delete %>
                    <% else %>
                        <%= link_to "フォローする", user_relationships_path(@book.user.id), class: "btn btn-default col-lg-12", method: :post %>
                    <% end %>
                <% end %>
            </div>

            <div>
            <%= link_to "", edit_user_path(@book.user), class: "glyphicon glyphicon-wrench btn btn-default col-lg-12", style:"color: black" %>
            </div>

        </div>


        <div class="row">
            <%= form_for(@book_new, url: books_path) do |f| %>
                <div>
                    <% if @book_new.errors.any? %>
                      <div id="error_explanation">
                        <h2><%= @book_new.errors.count %>件のエラーが発生しました。</h2>
                        <ul>
                            <% @book_new.errors.full_messages.each do |message| %>
                              <li><%= message %></li>
                            <% end %>
                        </ul>
                      </div>
                    <% end %>
                </div>

                <h1 class="">New book</h1>

                <div class="row">
                    <h5>Title</h5>
                    <div><%= f.text_field :title, class: "col-lg-12"  %></div>
                </div>

                <div class="row">
                    <h5>Opinion</h5>
                     <div><%= f.text_area :body, class: "col-lg-12"  %></div>
                </div>

                <div class="row">
                    <div style="margin-top: 10px;"><%= f.submit "Create Book", class: "btn btn-primary col-lg-12" %></div>
                </div>
            <% end %>

        </div>
    </div>

    <div class="<%= "detail-#{@book.id}"%> main col-lg-9" >
        <%= render 'book_detail.html.erb', book: @book, comment: @comment %>
    </div>

</div>