config/routes.rb
Rails.application.routes.draw do
  get 'search', to: "search#search"
  # get 'relationships/create'
  # get 'relationships/destroy'
  # get 'comments/create'
  # get 'comments/destroy'
  root to: 'users#home'
  # deviseのコントローラーをカスタマイズしたのでroutesを編集しないと反映されない
  devise_for :users, :controllers => {
    :registrations => 'users/registrations',
    :sessions => 'users/sessions'
  }

  resources :users do
    resource :relationships, only: [:create, :destroy]
    get :follows, on: :member
    get :followers, on: :member
  end

  resources :books do
    resource :favorites, only: [:create, :destroy]
    resource :comments, only: [:create, :destroy]
  end
  resources :home
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bookers2</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link href="https://use.fontawesome.com/releases/v5.6.1/css/all.css" rel="stylesheet">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <script type="text/javascript" src="//code.jquery.com/jquery-2.1.0.min.js"></script>
    <script type="text/javascript" src="//jpostal-1006.appspot.com/jquery.jpostal.js"></script>
  </head>

  <body>
    <header>
<nav class="navbar navbar-inverse">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbarEexample1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <div class="navbar-brand ", style="color: white;" >Bookers</div>
    </div>

<div class="collapse navbar-collapse" id="navbarEexample1">
      <ul class="nav navbar-nav navbar-right">
          <% if user_signed_in? %>
            <li class="">
              <span aria-hidden="true"></span>
              <%= link_to ' Home', user_path(current_user.id), data: {"turbolinks" => false}, class: "glyphicon glyphicon-home" %>
            </li>
            <li class="">
              <%= link_to ' Users', users_path, class: "glyphicon glyphicon-user" %>
            </li>
            <li class="">
              <%= link_to ' Books', books_path, class: "glyphicon glyphicon-book" %>
            </li>
            <li class="">
              <%= link_to " logout", destroy_user_session_path, method: :delete, class: "glyphicon glyphicon-log-out" %>
            </li>
          <% else %>
          <li class="">
              <%= link_to " Home", root_path, class: "glyphicon glyphicon-home" %>
            </li>
            <li class="">
              <%= link_to " About", '/home/about', class: "glyphicon glyphicon-link" %>
            </li>
            <li class="">
              <%= link_to " sign up", new_user_registration_path, class: "glyphicon glyphicon-edit" %>
            </li>
            <li class="">
              <%= link_to " login", new_user_session_path, class: "glyphicon glyphicon-log-in" %>
            </li>
          <% end %>
  </ul>

</div>
</div>
</nav>
    </header>
    <%= yield %>

<footer>
  <div class="container">
    <div class="row">
      <div class="col-xs-3 col-xs-offset-9">
        <p>CopyRight Infratop.inc</p>
      </div>
    </div>
  </div>
</footer>

  </body>
</html>